### ISSUE TITLE
Conversion stops abruptly midway overwriting original video with previous one

### ISSUE THREAD

**Issue by ParadiseOnEarth** [lucids-git-goods/DarkShadowPlayYouTubeFix#2]
During 2nd conversion in the same directory, ffmpeg.exe asked first if I want to override .temp file, which wasn't present before beginning. After declining and removing the file manually, the conversion launched without issue. After sometime it closed down while also removing the original file, overwriting it with the previous converted video.

**Comment by lucids-git-goods** [comment]
@ParadiseOnEarth Thanks for the heads up.  The new release should fix this issue:
https://github.com/lucids-git-goods/DarkShadowPlayYouTubeFix/releases
