### ISSUE TITLE
No context menu after installation

### ISSUE THREAD

**Issue by qb20nh** [lucids-git-goods/DarkShadowPlayYouTubeFix#3]
Using Windows 10 Pro 20H2 build 19042.746
```batch
@echo off
:: BatchGotAdmin
::-------------------------------------
~omitted~
::--------------------------------------

::ENTER YOUR CODE BELOW:


xcopy "DarkShadowPlayYouTubeFix.bat" "%ProgramFiles(x86)%\DarkShadowPlayYouTubeFix\DarkShadowPlayYouTubeFix.bat*"
if exist "ffmpeg.exe" xcopy "ffmpeg.exe" "%ProgramFiles(x86)%\DarkShadowPlayYouTubeFix\ffmpeg.exe*" 

SetLocal
for /f "tokens=2*" %%a in ('reg query "HKEY_CLASSES_ROOT\.mp4" /ve') do set progId=%%b
REG Add "HKEY_CLASSES_ROOT\%progId%\shell\FixShadowPlay" /f /ve /d "Prepare ShadowPlayed MP4 for YouTube"
REG Add "HKEY_CLASSES_ROOT\%progId%\shell\FixShadowPlay\command" /f /ve /d "\"%ProgramFiles(x86)%\\DarkShadowPlayYouTubeFix\\DarkShadowPlayYouTubeFix.bat\" \"%%1\""
```
Removed trimming one bc I don't need it
Running this on administrator cmd, this is the output
```
C:\Users\user\Downloads\DarkShadowPlayYoutubeFix>InstallDarkShadowPlayYouTubeFix.bat
C:DarkShadowPlayYouTubeFix.bat
1 File(s) copied
The operation completed successfully.
The operation completed successfully.
```
Registry after installation:
```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.mp4]
"Content Type"="video/mp4"
"PerceivedType"="video"

[HKEY_CLASSES_ROOT\.mp4\OpenWithProgids]
"AppX6eg8h5sxqq90pv53845wmnbewywdqq5h"=hex(0):
"AppXk0g4vb8gvt7b93tg50ybcy892pge6jmt"=hex(0):
"io.mpv.mpeg4"=""

[HKEY_CLASSES_ROOT\.mp4\shellex]

[HKEY_CLASSES_ROOT\.mp4\shellex\{00021500-0000-0000-C000-000000000046}]
@="{869C14C8-1830-491F-B575-5F9AB40D2B42}"

[HKEY_CLASSES_ROOT\.mp4\shellex\{BB2E617C-0920-11D1-9A0B-00C04FC2D6C1}]
@="{C5AEC3EC-E812-4677-A9A7-4FEE1F9AA000}"

[HKEY_CLASSES_ROOT\.mp4\shellex\{e357fccd-a995-4576-b01f-234630154e96}]
@="{C5AEC3EC-E812-4677-A9A7-4FEE1F9AA000}"

[HKEY_CLASSES_ROOT\(value not set)]

[HKEY_CLASSES_ROOT\(value not set)\shell]

[HKEY_CLASSES_ROOT\(value not set)\shell\FixShadowPlay]
@="Prepare ShadowPlayed MP4 for YouTube"

[HKEY_CLASSES_ROOT\(value not set)\shell\FixShadowPlay\command]
@="\"C:\\Program Files (x86)\\\\DarkShadowPlayYouTubeFix\\\\DarkShadowPlayYouTubeFix.bat\" \"%1\""
```

**Comment by lucids-git-goods** [comment]
hello hieroglyphic.  So is there not a key/value for:
[HKEY_CLASSES_ROOT\.mp4]
(Default)
?

The installation batch is looking for that value, which would take the place of (value not set).
As I understand it, it could vary depending on what was originally set to be the mp4 file association.  For instance, on my PC it's WMP11.AssocFile.MP4

**Comment by qb20nh** [comment]
Yeah default value is not set for most media file types.
I have set it to mpv in settings app (installed with scoop and mpv-install) and mp4 files opens with it.
Default program id seems to be stored here:
```reg
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.mp4\UserChoice]
"ProgId"="io.mpv.mpeg4"
"Hash"="sLUtRmPrM4w="
```
Merging `HKEY_CLASSES_ROOT\(value not set)` with existing `HKEY_CLASSES_ROOT\io.mpv.mpeg4` made it work.
Perhaps we could use this as a fallback
> it could vary depending on what was originally set to be the mp4 file association.

Does that mean if I change the default program associated with it, it will not appear?

**Comment by lucids-git-goods** [comment]
@hieroglyphic I believe it should continue to work even if you change the default application.   I will try to get another update out that falls back to check explorer/fileexts if it doesn't find it in the initial location in the near future.
Thanks for the help in figuring this out.

**Comment by lucids-git-goods** [comment]
pushed an update that will check in the userchoice section if it can't find the progId in the first location
