### ISSUE TITLE
Security issue with Windows Security's Controlled folder access

### ISSUE THREAD

**Issue by qb20nh** [lucids-git-goods/DarkShadowPlayYouTubeFix#5]
First time it gets blocked, the warning pops up and you have to allow cmd.exe.
The problem is this allows any program or script to run cmd.exe and access that specific folder.
I tried to encapsulate it with exe as mentioned [here](https://superuser.com/a/868341/300375) but it looks like the parameters are not being passed onto it properly.
The thing is there is this file named `mpv.com` in my mpv installation directory and it seems to be a kind of command line bridge, and usual command line stuff and parameters work fine with this. (It just opens up GUI if I invoke it with file path)
Is it possible to encapsulate batch file as a win32/dos executable in a way that is invisible to the script itself?

**Comment by lucids-git-goods** [comment]
That's a bit outside the scope of this project.  When I run it on my machine, UAC asked for permission each time I run the batch and there isn't a separate permission required.

**Comment by qb20nh** [comment]
[I found how to do it](https://stackoverflow.com/a/48272996/4592648)
It now comes down to allowing `ffmpeg.exe`
Maybe create a symlink at the batch file location and Windows Security will recognize it as a separate one.
Not sure if this makes anything better though since allowing once means allowing everywhere forever
