### ISSUE TITLE
Menu dosent shows up on latest windows 10

### ISSUE THREAD

**Issue by believer-ufa** [lucids-git-goods/DarkShadowPlayYouTubeFix#6]
Don't know why. Script successfully installed into Program Files, but it doesn't work, nothing added to context menu.

Anyway, thank you for your work!

**Comment by lucids-git-goods** [comment]
Hello.  Would you mind checking a couple of regedit entries for me?

HKEY_CLASSES_ROOT\.mp4
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.mp4\UserChoice

**Comment by believer-ufa** [comment]
Of course, sorry for long response.

My current `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts.mp4\UserChoice` is next:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.mp4\UserChoice]
"Hash"="VWtEmTXYkmA="
"ProgId"="VLC.mp4"
```

Tell me if you need something else for debugging.

**Comment by lucids-git-goods** [comment]
No problem.  Thanks.   And how about `HKEY_CLASSES_ROOT\.mp4` ?

**Comment by believer-ufa** [comment]
Oh yeah. This is it:

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.mp4]
@="VLC.mp4"
"Content Type"="video/mp4"
"PerceivedType"="video"

[HKEY_CLASSES_ROOT\.mp4\OpenWithProgids]
"AppX6eg8h5sxqq90pv53845wmnbewywdqq5h"=hex(0):
"AppXk0g4vb8gvt7b93tg50ybcy892pge6jmt"=hex(0):
"WMP11.AssocFile.MP4"=hex(0):

[HKEY_CLASSES_ROOT\.mp4\ShellEx]

[HKEY_CLASSES_ROOT\.mp4\ShellEx\{BB2E617C-0920-11D1-9A0B-00C04FC2D6C1}]
@="{9DBD2C50-62AD-11D0-B806-00C04FD706EC}"

[HKEY_CLASSES_ROOT\.mp4\ShellEx\{e357fccd-a995-4576-b01f-234630154e96}]
@="{9DBD2C50-62AD-11D0-B806-00C04FD706EC}"
```

**Comment by lucids-git-goods** [comment]
@believer-ufa Thanks again.  Last one for the registry entries.  Do you have anything at:
HKEY_CLASSES_ROOT\VLC.mp4\shell\FixShadowPlay  
and 
HKEY_CLASSES_ROOT\VLC.mp4\shell\FixShadowPlay\command  


and if not, then:
HKEY_CLASSES_ROOT\WMP11.AssocFile.MP4\shell\FixShadowPlay  
and 
HKEY_CLASSES_ROOT\WMP11.AssocFile.MP4\shell\FixShadowPlay\command

**Comment by believer-ufa** [comment]
I don't have `HKEY_CLASSES_ROOT\VLC.mp4\shell\FixShadowPlay` entry at all on my pc.
Same about `HKEY_CLASSES_ROOT\WMP11.AssocFile.MP4\shell\FixShadowPlay`.

![image](https://user-images.githubusercontent.com/801727/107562619-e2286f80-6c01-11eb-9f85-5cf59ca5c78a.png)
![image](https://user-images.githubusercontent.com/801727/107562669-f2404f00-6c01-11eb-9467-66553caf6884.png)

**Comment by lucids-git-goods** [comment]
Could you try adding this line: 
`echo %progId%| clip`
to line 38 of **InstallDarkShadowPlayYouTubeFix.bat**
(right before the line that says `if "%progId%" NEQ "(value not set)" (`)
that will copy a value to the clipboard, and then paste it here

**Comment by believer-ufa** [comment]
hm, strange, but then i ran your script through Far Manager with admin rights - it seems that its installed now successfully on my machine.

```
G:\Software\tools\DarkShadowPlayYoutubeFix>InstallDarkShadowPlayYouTubeFix.bat
Overwrite C:\Program Files (x86)\DarkShadowPlayYouTubeFix\DarkShadowPlayYouTubeFix.bat (Yes/No/All)? y
G:DarkShadowPlayYouTubeFix.bat
1 File(s) copied
Overwrite C:\Program Files (x86)\DarkShadowPlayYouTubeFix\DarkShadowPlayYouTubeFixWithTrim.bat (Yes/No/All)? y
G:DarkShadowPlayYouTubeFixWithTrim.bat
1 File(s) copied
Overwrite C:\Program Files (x86)\DarkShadowPlayYouTubeFix\ffmpeg.exe (Yes/No/All)? y
G:ffmpeg.exe
Sharing violation
VLC.mp4
\\DarkShadowPlayYouTubeFix\\DarkShadowPlayYouTubeFix.bat\" \"%1\"" was unexpected at this time.
```

this is is my output from Far Manager. thank you for your support! )

**Comment by lucids-git-goods** [comment]
@believer-ufa Nice.  Glad it's working.  One last question though in case I need to update the documentation: 
Did you have to right click and run as admin?  or did you just click yes when it asked automatically?

**Comment by believer-ufa** [comment]
I ran Far manually with admin rights, yes. And after it everything installed correctly.

First time i ran it without admin permissions and (even if your script then asked for them) it seems that it was main problem of incorrect installation.

**Comment by lucids-git-goods** [comment]
ah k.  Thanks for your help!
